### PR TITLE
Support template-haskell 2.17, plus unlifted fix.

### LINKED ISSUE #43: deriveLift-generated instance for unlifted newtype fails to typecheck
The following should work on GHC 8.10 or later, but doesn't:

```hs
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE UnliftedNewtypes #-}
{-# OPTIONS_GHC -ddump-splices #-}
module Bug where

import GHC.Exts
import Language.Haskell.TH.Lift

newtype T = MkT Int#
$(deriveLift ''T)
```
```
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )
Bug.hs:11:3-16: Splicing declarations
    deriveLift ''T
  ======>
    instance Lift T where
      lift
        = \ e_a4bz
            -> case e_a4bz of {
                 MkT x0_a4bA
                   -> (Language.Haskell.TH.Lib.Internal.appE
                         (Language.Haskell.TH.Lib.Internal.conE
                            ((Language.Haskell.TH.Syntax.Name
                                (Language.Haskell.TH.Syntax.mkOccName "MkT"))
                               (((Language.Haskell.TH.Syntax.NameG
                                    Language.Haskell.TH.Syntax.DataName)
                                   (Language.Haskell.TH.Syntax.mkPkgName "fake-package-0-inplace"))
                                  (Language.Haskell.TH.Syntax.mkModName "Bug")))))
                        (Language.Haskell.TH.Lib.Internal.litE
                           (Language.Haskell.TH.Lib.Internal.intPrimL
                              (toInteger (I# x0_a4bA)))) }
      liftTyped = (Language.Haskell.TH.Syntax.unsafeTExpCoerce . lift)

Bug.hs:11:3: error:
    • Couldn't match a lifted type with an unlifted type
      When matching types
        t0 :: *
        T :: TYPE 'IntRep
      Expected type: T
                     -> Language.Haskell.TH.Syntax.Q (Language.Haskell.TH.Syntax.TExp T)
        Actual type: t0
                     -> Language.Haskell.TH.Syntax.Q (Language.Haskell.TH.Syntax.TExp T)
    • In the expression:
        (Language.Haskell.TH.Syntax.unsafeTExpCoerce . lift)
      In an equation for ‘liftTyped’:
          liftTyped = (Language.Haskell.TH.Syntax.unsafeTExpCoerce . lift)
      In the instance declaration for ‘Lift T’
   |
11 | $(deriveLift ''T)
   |   ^^^^^^^^^^^^^^
```

The issue is rather silly: the use of `(.)` in `liftTyped = unsafeTExpCoerce . lift` forces the types to be lifted instead of using `TYPE 'IntRep`. Simply generating `liftTyped = \x -> unsafeTExpCoerce (lift x)` instead would fix the issue.

### PR DESCRIPTION
**Pull request by galenhuntington**
Most changes are to use the new `Code` newtype (https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3358).

Also, while I was in there I took the opportunity to fix #43.

Note that I had to use your [`explicit-specificity`](https://github.com/glguy/th-abstraction/pull/83) branch of `th-abstraction` to build, since it's a dependency.  Bounds adjusted accordingly.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks for the PR. Do note that I already have a [`quote`](https://github.com/RyanGlScott/th-lift/tree/quote) branch in the works which aims to solve this same problem, but it performs some additional refactoring to minimize the amount of CPP that needs to be used.

**Comment by galenhuntington** [comment]
Ah, I didn't see that.

**Comment by galenhuntington** [comment]
From the looks of it, there's nothing new in this PR then, so I'll close.

**Comment by RyanGlScott** [comment]
Admittedly, branches aren't the most easily discoverable things. I've opened #45 with the current state of the `quote` branch to more widely advertise its existence. With luck, that branch should continue to work once GHC 9.0.1-alpha1 is released.
